### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [identicalsnowflake/identicalsnowflake.github.io#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by identicalsnowflake** [comment]
I added a `feed.xml` to the repository root, but despite Github [explicitly saying they support this](https://help.github.com/articles/atom-rss-feeds-for-github-pages/), I got a 404. Renaming it to `atom-feed.xml` seems to work.

Does https://identicalsnowflake.github.io/atom-feed.xml look correct? I've never published atom before, so if something is missing or wrong, let me know.

**Comment by tfausak** [comment]
That works great, thanks!
